### ISSUE TITLE
"Node" class in "include.py"

### ISSUE THREAD

**Issue by HaokunLi1994** [jkeller51/CS448_MP1#1]
It seems like without x and y coordinates, it's difficult to define "children" (which means 4 characters next to the current "Node") of a particular "Node".

**Comment by jkeller51** [comment]
If we store the nodes as `maze[x][y] = Node(...)`

Then the x,y are defined as the location inside the "matrix", maze. So if we keep track of (x,y) at the top level, we can find the children by looking for maze[x+1][y], maze[x][y+1], etc. This would make storing x and y inside the Node object redundant.

**Comment by HaokunLi1994** [comment]
What do you mean by "keep track of (x,y) at the top level"? Let's say, here we're given a Node named "A", then in order to find all children nodes of "A", how do we get (x, y) of "A"?

**Comment by jkeller51** [comment]
```python
def greedy_move(Matrix,x,y):
   # x, y are "top level" coordinates
   # find the lowest cost adjacent tile

   rightcost = Matrix[x+1][y].cost
   mincost = rightcost
   minpos = (x+1,y)

   leftcost = Matrix[x-1][y].cost
   if (leftcost < mincost):
      minpos = (x-1,y)
      mincost = leftcost

   upcost = Matrix[x][y-1].cost
   if (upcost< mincost):
      minpos = (x,y-1)
      mincost = leftcost

   downcost = Matrix[x][y+1].cost
   .......... # similar logic to above

   return minpos
   
```

**Comment by jkeller51** [comment]
It's basically the difference between passing around references to node objects (what you're thinking), where we will need the object to have coordinate variables, or passing around the coordinates themselves, which lead us to the corresponding node objects, which don't need coordinate variables because we already have the coordinates.

**Comment by HaokunLi1994** [comment]
Ah, gotcha! But the tricky part here is, it's hard to keep track of x and y on top level when using BFS. When implementing BFS, I'll need to push a node's all children into a queue. Then without bundle all the information (coordinates and characters) together, I couldn't find a way to figure out what x and y values are for each child.

**Comment by jkeller51** [comment]
I see the issue. Let's give the Nodes x,y variables.

**Comment by HaokunLi1994** [comment]
Thanks bro!
